modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="yatcm" #mandatory
version="1.20.1-1.0.0.0" #mandatory
displayName="Yet Another Tiny Coal Mod" #mandatory
authors="Steven 'specCon18' Carpenter" #optional
description='''yet another tiny coal mod. I haven't touched modding since 1.4.7 and want to pick it back up.''' #mandatory
